[project]
name = "flagrant-client"
version = "0.1.0"
description = "A python client for Flagrant feature-flagging API"
readme = "README.md"
license = "MIT"
authors = [
    { name = "Michal Buczko", email = "michal@buczko.pl" }
]
requires-python = ">=3.11"
classifiers = [
    "Development Status :: 4 - Beta",
    "Environment :: Console",
]
dependencies = [
    "grpcio>=1.83.0",
    "httpx>=0.28.1",
    "protobuf>=7.36.0",
    "pydantic>=2.13.4",
]

[project.urls]
Homepage = "https://github.com/mbuczko/flagrant-client-python"
Repository = "https://github.com/mbuczko/flagrant-client-python"

[tool.hatch.build.targets.wheel]
packages = ["src/flagrant"]

[tool.ruff]
extend-exclude = ["src/flagrant/proto/*_pb2.py", "src/flagrant/proto/*_pb2_grpc.py"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = [
    "grpcio-tools>=1.83.0",
    "ipython>=9.16.1",
]
