# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import features_pb2 as features__pb2

GRPC_GENERATED_VERSION = '1.83.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in features_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class FeatureResolverStub:
    """Mirrors GET /api/v1/projects/{project}/envs/{environment}/features.

    Identity is sent via the `x-flagrant-identity` gRPC metadata key (mirroring the
    `X-Flagrant-Identity` HTTP header), and the srv-token via the standard `authorization`
    metadata key as `Bearer <token>` (mirroring the HTTP `Authorization` header) - neither
    is a message field, same reasoning as HTTP headers not being query/body params.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetFeatures = channel.unary_unary(
                '/flagrant.v1.FeatureResolver/GetFeatures',
                request_serializer=features__pb2.GetFeaturesRequest.SerializeToString,
                response_deserializer=features__pb2.GetFeaturesResponse.FromString,
                _registered_method=True)


class FeatureResolverServicer:
    """Mirrors GET /api/v1/projects/{project}/envs/{environment}/features.

    Identity is sent via the `x-flagrant-identity` gRPC metadata key (mirroring the
    `X-Flagrant-Identity` HTTP header), and the srv-token via the standard `authorization`
    metadata key as `Bearer <token>` (mirroring the HTTP `Authorization` header) - neither
    is a message field, same reasoning as HTTP headers not being query/body params.
    """

    def GetFeatures(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FeatureResolverServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetFeatures': grpc.unary_unary_rpc_method_handler(
                    servicer.GetFeatures,
                    request_deserializer=features__pb2.GetFeaturesRequest.FromString,
                    response_serializer=features__pb2.GetFeaturesResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'flagrant.v1.FeatureResolver', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('flagrant.v1.FeatureResolver', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class FeatureResolver:
    """Mirrors GET /api/v1/projects/{project}/envs/{environment}/features.

    Identity is sent via the `x-flagrant-identity` gRPC metadata key (mirroring the
    `X-Flagrant-Identity` HTTP header), and the srv-token via the standard `authorization`
    metadata key as `Bearer <token>` (mirroring the HTTP `Authorization` header) - neither
    is a message field, same reasoning as HTTP headers not being query/body params.
    """

    @staticmethod
    def GetFeatures(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/flagrant.v1.FeatureResolver/GetFeatures',
            features__pb2.GetFeaturesRequest.SerializeToString,
            features__pb2.GetFeaturesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
