# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: features.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'features.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x66\x65\x61tures.proto\x12\x0b\x66lagrant.v1\":\n\x12GetFeaturesRequest\x12\x0f\n\x07project\x18\x01 \x01(\t\x12\x13\n\x0b\x65nvironment\x18\x02 \x01(\t\"=\n\x13GetFeaturesResponse\x12&\n\x08\x66\x65\x61tures\x18\x01 \x03(\x0b\x32\x14.flagrant.v1.Feature\"}\n\x07\x46\x65\x61ture\x12\x12\n\nfeature_id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12(\n\x05value\x18\x03 \x01(\x0b\x32\x19.flagrant.v1.VariantValue\x12\x17\n\nis_enabled\x18\x04 \x01(\x08H\x00\x88\x01\x01\x42\r\n\x0b_is_enabled\"F\n\x0cVariantValue\x12\x0e\n\x04text\x18\x01 \x01(\tH\x00\x12\x0e\n\x04json\x18\x02 \x01(\tH\x00\x12\x0e\n\x04toml\x18\x03 \x01(\tH\x00\x42\x06\n\x04kind2c\n\x0f\x46\x65\x61tureResolver\x12P\n\x0bGetFeatures\x12\x1f.flagrant.v1.GetFeaturesRequest\x1a .flagrant.v1.GetFeaturesResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'features_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GETFEATURESREQUEST']._serialized_start=31
  _globals['_GETFEATURESREQUEST']._serialized_end=89
  _globals['_GETFEATURESRESPONSE']._serialized_start=91
  _globals['_GETFEATURESRESPONSE']._serialized_end=152
  _globals['_FEATURE']._serialized_start=154
  _globals['_FEATURE']._serialized_end=279
  _globals['_VARIANTVALUE']._serialized_start=281
  _globals['_VARIANTVALUE']._serialized_end=351
  _globals['_FEATURERESOLVER']._serialized_start=353
  _globals['_FEATURERESOLVER']._serialized_end=452
# @@protoc_insertion_point(module_scope)
